export const manseryeokValidationSamples = [
  // expected/referenceSource는 외부 만세력 기준값을 수동 확인한 뒤에만 채웁니다.
  // lunar-javascript actual 결과를 expected에 복사해 정답처럼 사용하지 않습니다.
  {
  id: 'solar_regular_known_time',
  title: '양력 일반 생시 있음',
  profile: {
    nickname: '검증샘플A',
    birthDate: '1990-05-15',
    birthTime: '09:30',
    birthTimeUnknown: false,
    calendarType: 'solar',
    isLeapMonth: false,
    gender: 'male',
  },
  expected: {
    pillars: {
      year: '경오',
      month: '신사',
      day: '경진',
      hour: '신사',
    },
    dayMaster: {
      stem: '경',
    },
    convertedSolar: '1990-05-15 09:30:00',
  },
  referenceStatus: 'reference_verified',
  referenceSource: {
    name: 'sky.told.me',
    url: null,
    checkedAt: '2026-06-08',
    checkedBy: 'manual',
    memo:
  'sky.told.me 입력 기준: 남성, 양력 1990-05-15 09:30, 출생도시 Seoul, South Korea. 四柱八字 결과 기준. convertedLunar는 결과에서 명확히 확인되지 않아 미입력. 태양시 보정 여부는 추가 확인 필요.',
  },
  notes: [
    '외부 만세력 기준값 1차 입력',
    '四柱八字 결과만 expected에 반영',
    '대운, 신살, 자미두수, Natal Chart는 현재 검증 범위에서 제외',
    '출생도시 입력값과 태양시 보정 여부 추가 확인 필요',
  ],
},
  {
    id: 'solar_unknown_time',
    title: '양력 시간 미상',
    profile: {
      nickname: '검증샘플B',
      birthDate: '1988-10-03',
      birthTime: '',
      birthTimeUnknown: true,
      calendarType: 'solar',
      isLeapMonth: false,
      gender: 'other',
    },
    expected: null,
    referenceStatus: 'reference_pending',
    referenceSource: null,
    notes: ['시주가 확정값처럼 표시되지 않아야 함', '내부 계산용 12:00 사용 여부 확인'],
  },
  {
    id: 'solar_after_23',
    title: '양력 23시 이후 출생',
    profile: {
      nickname: '검증샘플C',
      birthDate: '1992-07-20',
      birthTime: '23:30',
      birthTimeUnknown: false,
      calendarType: 'solar',
      isLeapMonth: false,
      gender: 'other',
    },
    expected: null,
    referenceStatus: 'reference_pending',
    referenceSource: null,
    notes: ['23시 이후 자시 기준 정책 검토 필요', '외부 만세력과 일주/시주 비교 필요'],
  },
  {
    id: 'solar_before_ipchun',
    title: '양력 입춘 전 샘플',
    profile: {
      nickname: '검증샘플D-1',
      birthDate: '1990-02-03',
      birthTime: '23:30',
      birthTimeUnknown: false,
      calendarType: 'solar',
      isLeapMonth: false,
      gender: 'male',
    },
    expected: null,
    referenceStatus: 'reference_conflict',
    referenceSource: {
      name: 'sky.told.me / 포스텔러',
      url: null,
      checkedAt: '2026-06-08',
      checkedBy: 'manual',
      memo:
        '1990-02-03 23:30 Seoul 기준에서 sky.told.me와 포스텔러 결과가 불일치. sky.told.me는 기사년 정축월 경자일 병자시, 포스텔러는 기사년 정축월 기해일 을해시로 표시됨. 23시 이후 자시 기준, 야자시/조자시, 태양시 보정 여부 확인 필요.',
    },
    notes: [
      '외부 기준값 충돌 샘플',
      'sky.told.me: 기사년 정축월 경자일 병자시',
      '포스텔러: 기사년 정축월 기해일 을해시',
      '23:30 출생의 자시 처리 기준과 태양시 보정 여부 확인 필요',
      '충돌 상태이므로 expected는 입력하지 않음',
    ],
  },
  {
    id: 'solar_ipchun_boundary',
    title: '양력 입춘 전후 절기 경계',
    profile: {
      nickname: '검증샘플D',
      birthDate: '1990-02-04',
      birthTime: '10:30',
      birthTimeUnknown: false,
      calendarType: 'solar',
      isLeapMonth: false,
      gender: 'male',
    },
    expected: {
      pillars: {
        year: '기사',
        month: '정축',
        day: '경자',
        hour: '신사',
      },
      dayMaster: {
        stem: '경',
      },
      convertedSolar: '1990-02-04 10:30:00',
    },
    referenceStatus: 'reference_verified',
    referenceSource: {
      name: 'sky.told.me / 포스텔러',
      url: null,
      checkedAt: '2026-06-08',
      checkedBy: 'manual',
      memo:
        '남성, 양력 1990-02-04 10:30, 출생도시 Seoul, South Korea 기준. sky.told.me와 포스텔러 四柱八字 결과가 기사년 정축월 경자일 신사시로 일치함. convertedLunar는 결과에서 명확히 확인되지 않아 미입력.',
    },
    notes: [
      '입춘 경계 샘플 외부 기준값 입력',
      'sky.told.me와 포스텔러 결과 일치',
      '四柱八字 결과만 expected에 반영',
      '대운, 신살, 자미두수, Natal Chart는 현재 검증 범위에서 제외',
    ],
  },
  {
    id: 'solar_after_ipchun',
    title: '양력 입춘 후 샘플',
    profile: {
      nickname: '검증샘플D-2',
      birthDate: '1990-02-05',
      birthTime: '00:30',
      birthTimeUnknown: false,
      calendarType: 'solar',
      isLeapMonth: false,
      gender: 'male',
    },
    expected: {
      pillars: {
        year: '경오',
        month: '무인',
        day: '신축',
        hour: '무자',
      },
      dayMaster: {
        stem: '신',
      },
      convertedSolar: '1990-02-05 00:30:00',
    },
    referenceStatus: 'reference_verified',
    referenceSource: {
      name: 'sky.told.me / 포스텔러',
      url: null,
      checkedAt: '2026-06-08',
      checkedBy: 'manual',
      memo:
        '남성, 양력 1990-02-05 00:30, 출생도시 Seoul, South Korea 기준. sky.told.me와 포스텔러 四柱八字 결과가 경오년 무인월 신축일 무자시로 일치함. convertedLunar는 결과에서 명확히 확인되지 않아 미입력.',
    },
    notes: [
      '입춘 후 샘플 외부 기준값 입력',
      'sky.told.me와 포스텔러 결과 일치',
      '四柱八字 결과만 expected에 반영',
      '대운, 신살, 자미두수, Natal Chart는 현재 검증 범위에서 제외',
    ],
  },
  {
    id: 'lunar_regular',
    title: '음력 일반',
    profile: {
      nickname: '검증샘플E',
      birthDate: '1990-01-20',
      birthTime: '08:00',
      birthTimeUnknown: false,
      calendarType: 'lunar',
      isLeapMonth: false,
      gender: 'other',
    },
    expected: null,
    referenceStatus: 'reference_pending',
    referenceSource: null,
    notes: ['음력에서 양력 변환 결과 비교 필요', '윤달이 아닌 일반 음력 케이스'],
  },
  {
    id: 'lunar_leap_candidate',
    title: '음력 윤달 후보',
    profile: {
      nickname: '검증샘플F',
      birthDate: '2023-02-01',
      birthTime: '12:00',
      birthTimeUnknown: false,
      calendarType: 'lunar',
      isLeapMonth: true,
      gender: 'other',
    },
    expected: null,
    referenceStatus: 'reference_pending',
    referenceSource: null,
    notes: ['윤달 입력 처리 확인', '외부 만세력 기준 변환일 비교 필요'],
  },
  {
    id: 'solar_before_23',
    title: '양력 23시 직전 출생',
    profile: {
      nickname: '검증샘플C-1',
      birthDate: '1992-07-20',
      birthTime: '22:30',
      birthTimeUnknown: false,
      calendarType: 'solar',
      isLeapMonth: false,
      gender: 'other',
    },
    expected: null,
    referenceStatus: 'reference_pending',
    referenceSource: null,
    notes: ['23시 이전 샘플', '23시 이후 샘플과 일주/시주 비교 필요'],
  },
  {
    id: 'invalid_time',
    title: '잘못된 시간 입력',
    profile: {
      nickname: '검증샘플G',
      birthDate: '1990-05-15',
      birthTime: '25:99',
      birthTimeUnknown: false,
      calendarType: 'solar',
      isLeapMonth: false,
      gender: 'other',
    },
    expected: null,
    referenceStatus: 'not_applicable',
    referenceSource: null,
    notes: ['입력 오류 검증용 샘플', '계산 실패가 전체 검증 중단으로 이어지지 않아야 함'],
  },
  {
    id: 'invalid_date',
    title: '잘못된 날짜 입력',
    profile: {
      nickname: '검증샘플H',
      birthDate: 'not-a-date',
      birthTime: '09:00',
      birthTimeUnknown: false,
      calendarType: 'solar',
      isLeapMonth: false,
      gender: 'other',
    },
    expected: null,
    referenceStatus: 'not_applicable',
    referenceSource: null,
    notes: ['입력 오류 검증용 샘플', '날짜 파싱 실패가 calculation_failed로 표시되어야 함'],
  },
];
