import fs from 'node:fs';

const docPath = 'docs/RELEASE_AAB_GENERATION_RECORD.md';

const requiredDocSnippets = [
  '# Release AAB Generation Record',
  'Status: Release AAB generation recorded',
  'Release signing config: Completed',
  'GitHub Secrets final input: Completed',
  'Release AAB workflow: Completed',
  'Release build: Completed',
  'AAB generation: Completed',
  'Release AAB verification: Completed',
  'Release AAB artifact download: Completed',
  'Google Play AAB upload: Not started',
  'App submission/review request: Pending',
  'Purpose: Record release AAB workflow success and artifact generation',
  'PR type: docs/check-only',
  'This record is finalized against Android Release AAB workflow run #9 (success), superseding the earlier run reference recorded in PR #389',
  'Release AAB was generated by GitHub Actions',
  'Release AAB artifact was generated and verified',
  'Release AAB artifact download was confirmed',
  'This PR does not commit AAB files',
  'This PR does not add real keystore files',
  'This PR does not add signing credentials',
  'This PR does not upload AAB to Google Play Console',
  'This PR does not submit the app for review',
  'This PR does not change production UI or app logic',
  '## 2. Completed release AAB items',
  '| GitHub Secrets final input | Completed | Required signing secrets registered in GitHub Secrets |',
  '| Release AAB workflow | Completed | Manual GitHub Actions workflow run succeeded |',
  '| Release build | Completed | Completed by Android Release AAB workflow |',
  '| AAB generation | Completed | Release AAB artifact generated |',
  '| Release AAB verification | Completed | jarsigner verification passed |',
  '| Release AAB artifact download | Completed | Artifact confirmed downloadable from GitHub Actions |',
  '## 3. Artifact record',
  '| Workflow name | Android Release AAB |',
  '| Workflow run number | #9 |',
  '| Workflow result | success |',
  '| Build signed release AAB | success |',
  '| Verify signed release AAB | success |',
  '| Upload release AAB | success |',
  '| Artifact name | harupuli-release-aab |',
  '| AAB file name | app-release.aab |',
  '| AAB committed to repo | NO |',
  '| Artifact download | Confirmed |',
  '## 4. Not included in this PR',
  'No AAB file committed',
  'No real keystore file',
  'No signing credentials',
  'No committed secrets',
  'No Google Play AAB upload',
  'No app submission/review request',
  'No image file changes',
  'No new screenshot capture',
  'No new image generation',
  'No image redesign',
  'No src changes',
  'No CSS changes',
  'No AndroidManifest.xml changes',
  'No Android native/resource changes',
  'No fortune copy/content changes',
  'No fortune calculation logic changes',
  'No routing changes',
  'No schemaVersion changes',
  'No CURRENT_FORTUNE_SCHEMA_VERSION changes',
  'No existing localStorage key changes',
  '| Google Play AAB upload | Not started |',
  '| App submission/review request | Pending |',
  'This PR records release AAB generation and verification completion only.',
  'Google Play AAB upload and app submission/review request remain Pending/Not started.',
  'No AAB file, keystore file, signing credential, production UI, fortune logic, routing, schemaVersion, localStorage key, image, AAB upload, or app submission changes are included.',
];

const wrongPhrases = [
  '\u{AE08}(\u{91D1})',
  '실제 스토어 스크린샷 이미지 시작',
  '서양식 보정 적용 여부',
  '양력/음력 샘플 추가 검증',
  'Google Play AAB upload: Completed',
  'Google Play AAB upload | Completed',
  'Google Play AAB upload 완료',
  'App submission/review request: Completed',
  'App submission/review request | Completed',
  'app submission/review request 완료',
  'AAB committed to repo | YES',
  'keystore file committed',
  'signing credentials committed',
];

const requiredTodoSnippets = [
  '- [x] GitHub Secrets final input',
  '- [x] Release AAB workflow',
  '- [x] Release build',
  '- [x] AAB generation',
  '- [x] Release AAB verification',
  '- [x] release AAB generation completion 기록',
  '- [x] release AAB generation record 검증 스크립트 추가',
  '- [x] Release AAB workflow success 확인',
  '- [x] Release AAB artifact 생성 확인',
  '- [x] AAB 파일명 확인',
  '- [x] release AAB artifact 다운로드 가능 확인',
];

const pendingTodoSnippets = ['- [ ] Google Play AAB upload', '- [ ] App submission/review request'];

const requiredDevLogSnippets = [
  '## Release AAB Generation Record',
  'PR 목적: release AAB generation completion 기록',
  'Status: Docs/check-only',
  'GitHub Secrets final input: Completed',
  'Release AAB workflow: Completed',
  'Release build: Completed',
  'AAB generation: Completed',
  'Release AAB verification: Completed',
  'Google Play AAB upload: Not started',
  'App submission/review request: Pending',
  'AAB committed to repo: NO',
  '실제 keystore 파일 추가 없음',
  'signing credentials 추가 없음',
  'committed secrets 없음',
  'Google Play AAB upload 없음',
  'app submission/review request 없음',
  'production UI 변경 없음',
  'src 변경 없음',
  'CSS 파일 변경 없음',
  'AndroidManifest.xml 변경 없음',
  'Android native/resource 변경 없음',
  '운세 문구/content 변경 없음',
  '운세 계산 로직 변경 없음',
  'routing 변경 없음',
  'schemaVersion 변경 없음',
  'CURRENT_FORTUNE_SCHEMA_VERSION 변경 없음',
  '기존 localStorage key 변경 없음',
];

const requiredFinalizationDevLogSnippets = [
  '## Release AAB Generation Finalization',
  'PR 목적: release AAB generation record 실제 확인값 정정/확정',
  'Status: Docs/check-only',
  'Workflow name: Android Release AAB',
  'Workflow run number: #9',
  'Workflow result: success',
  'Release AAB workflow: Completed',
  'Release build: Completed',
  'AAB generation: Completed',
  'Release AAB verification: Completed',
  'Release AAB artifact download: Completed',
  'Google Play AAB upload: Not started',
  'App submission/review request: Pending',
  'AAB committed to repo: NO',
  '실제 AAB 파일 추가 없음',
  '실제 keystore 파일 추가 없음',
  'signing credentials 추가 없음',
  'committed secrets 없음',
  'Google Play AAB upload 없음',
  'app submission/review request 없음',
  'production UI 변경 없음',
  'src/CSS/Android/Gradle/Capacitor 변경 없음',
  '운세 로직/routing/schemaVersion/localStorage key 변경 없음',
];

const requiredChangelogSnippets = [
  'Recorded release AAB generation and verification completion.',
  'Added release AAB generation record check.',
  'Finalized release AAB generation record with actual Android Release AAB #9 success confirmation.',
];

const requiredPackageJsonSnippets = [
  '"check:release-aab-generation-record": "node scripts/checkReleaseAabGenerationRecord.mjs"',
];

let hasFailure = false;

function logResult(name, passed, detail = '') {
  const status = passed ? 'PASS' : 'FAIL';
  console.log(`[${status}] ${name}${detail ? ` - ${detail}` : ''}`);
  if (!passed) hasFailure = true;
}

function labelFromSnippet(snippet) {
  return snippet
    .replaceAll(/\s+/g, '_')
    .replaceAll(/[^\p{L}\p{N}_/-]/gu, '')
    .slice(0, 80);
}

logResult('doc_exists', fs.existsSync(docPath));
if (!fs.existsSync(docPath)) {
  console.error('Release AAB generation record check failed.');
  process.exit(1);
}

const doc = fs.readFileSync(docPath, 'utf8');
const todo = fs.readFileSync('TODO.md', 'utf8');
const devLog = fs.readFileSync('DEVELOPMENT_LOG.md', 'utf8');
const changelog = fs.readFileSync('CHANGELOG.md', 'utf8');
const packageJson = fs.readFileSync('package.json', 'utf8');

function sectionText(markdown, heading) {
  const start = markdown.indexOf(heading);
  if (start === -1) return '';
  const nextHeading = markdown.indexOf('\n## ', start + heading.length);
  return nextHeading === -1 ? markdown.slice(start) : markdown.slice(start, nextHeading);
}

for (const snippet of requiredDocSnippets) {
  logResult(`doc_includes_${labelFromSnippet(snippet)}`, doc.includes(snippet));
}

// docs/RELEASE_AAB_GENERATION_RECORD.md and CHANGELOG.md have no history of legitimately
// referencing these wrong phrases, so a whole-file scan is safe for them. TODO.md and
// DEVELOPMENT_LOG.md are running logs with legitimate past mentions (e.g. documenting that
// a check for these phrases exists), so their scan is scoped to this PR's section only.
const todoSection = sectionText(todo, '## Release AAB Generation Record TODO');
const devLogSection = sectionText(devLog, '## Release AAB Generation Record');
const finalizationDevLogSection = sectionText(devLog, '## Release AAB Generation Finalization');

logResult('todo_has_section', todoSection.length > 0);
logResult('dev_log_has_section', devLogSection.length > 0);
logResult('dev_log_has_finalization_section', finalizationDevLogSection.length > 0);

for (const file of [
  ['doc', doc],
  ['todo_section', todoSection],
  ['dev_log_section', devLogSection],
  ['finalization_dev_log_section', finalizationDevLogSection],
  ['changelog', changelog],
]) {
  const [label, content] = file;
  for (const phrase of wrongPhrases) {
    logResult(`${label}_excludes_${labelFromSnippet(phrase)}`, !content.includes(phrase));
  }
}

for (const snippet of requiredTodoSnippets) {
  logResult(`todo_includes_${labelFromSnippet(snippet)}`, todo.includes(snippet));
}

for (const snippet of pendingTodoSnippets) {
  logResult(`todo_keeps_pending_${labelFromSnippet(snippet)}`, todo.includes(snippet));
}

for (const snippet of requiredDevLogSnippets) {
  logResult(`dev_log_includes_${labelFromSnippet(snippet)}`, devLog.includes(snippet));
}

for (const snippet of requiredFinalizationDevLogSnippets) {
  logResult(`dev_log_finalization_includes_${labelFromSnippet(snippet)}`, finalizationDevLogSection.includes(snippet));
}

for (const snippet of requiredChangelogSnippets) {
  logResult(`changelog_includes_${labelFromSnippet(snippet)}`, changelog.includes(snippet));
}

for (const snippet of requiredPackageJsonSnippets) {
  logResult(`package_json_includes_${labelFromSnippet(snippet)}`, packageJson.includes(snippet));
}

// Guard against real AAB/keystore files or password-like literal assignments entering the repo.
const binaryFileReferencePattern = /["'][^"'\s]+\.(aab|jks|keystore|p12|pem)["']/i;
const passwordAssignmentPattern = /(storePassword|keyPassword|keystorePassword)\s*[:=]\s*['"][^'"\s]{3,}['"]/;
logResult('doc_excludes_binary_file_reference', !binaryFileReferencePattern.test(doc));
logResult('doc_excludes_password_assignment', !passwordAssignmentPattern.test(doc));

if (hasFailure) {
  console.error('Release AAB generation record check failed.');
  process.exit(1);
}

console.log('Release AAB generation record check passed');
